"""Ground-truth zone reference data used across ML components."""

from __future__ import annotations

from typing import Dict, List

ZONES: List[Dict[str, object]] = [
    # Mumbai
    {
        "zone_id": "MUM-AND-W",
        "zone": "Andheri West",
        "city": "Mumbai",
        "lat": 19.1136,
        "lng": 72.8697,
        "zone_multiplier": 1.40,
        "is_coastal": True,
        "avg_elevation_m": 11,
        "historical_rain_days": 85,
        "historical_aqi_gt300_days": 5,
        "historical_heat_gt44_days": 2,
    },
    {
        "zone_id": "MUM-AND-E",
        "zone": "Andheri East",
        "city": "Mumbai",
        "lat": 19.1197,
        "lng": 72.8799,
        "zone_multiplier": 1.30,
        "is_coastal": False,
        "avg_elevation_m": 14,
        "historical_rain_days": 80,
        "historical_aqi_gt300_days": 5,
        "historical_heat_gt44_days": 2,
    },
    {
        "zone_id": "MUM-BAN",
        "zone": "Bandra",
        "city": "Mumbai",
        "lat": 19.0596,
        "lng": 72.8295,
        "zone_multiplier": 1.35,
        "is_coastal": True,
        "avg_elevation_m": 9,
        "historical_rain_days": 82,
        "historical_aqi_gt300_days": 4,
        "historical_heat_gt44_days": 1,
    },
    {
        "zone_id": "MUM-DAH",
        "zone": "Dahisar",
        "city": "Mumbai",
        "lat": 19.2494,
        "lng": 72.8567,
        "zone_multiplier": 1.20,
        "is_coastal": False,
        "avg_elevation_m": 18,
        "historical_rain_days": 75,
        "historical_aqi_gt300_days": 8,
        "historical_heat_gt44_days": 3,
    },
    {
        "zone_id": "MUM-KUR",
        "zone": "Kurla",
        "city": "Mumbai",
        "lat": 19.0726,
        "lng": 72.8789,
        "zone_multiplier": 1.25,
        "is_coastal": False,
        "avg_elevation_m": 12,
        "historical_rain_days": 78,
        "historical_aqi_gt300_days": 10,
        "historical_heat_gt44_days": 3,
    },
    {
        "zone_id": "MUM-THN",
        "zone": "Thane",
        "city": "Mumbai",
        "lat": 19.2183,
        "lng": 72.9781,
        "zone_multiplier": 1.15,
        "is_coastal": False,
        "avg_elevation_m": 22,
        "historical_rain_days": 70,
        "historical_aqi_gt300_days": 12,
        "historical_heat_gt44_days": 4,
    },
    # Delhi
    {
        "zone_id": "DEL-CON",
        "zone": "Connaught Place",
        "city": "Delhi",
        "lat": 28.6315,
        "lng": 77.2167,
        "zone_multiplier": 1.30,
        "is_coastal": False,
        "avg_elevation_m": 216,
        "historical_rain_days": 28,
        "historical_aqi_gt300_days": 62,
        "historical_heat_gt44_days": 18,
    },
    {
        "zone_id": "DEL-LAJ",
        "zone": "Lajpat Nagar",
        "city": "Delhi",
        "lat": 28.5677,
        "lng": 77.2430,
        "zone_multiplier": 1.25,
        "is_coastal": False,
        "avg_elevation_m": 211,
        "historical_rain_days": 26,
        "historical_aqi_gt300_days": 58,
        "historical_heat_gt44_days": 16,
    },
    {
        "zone_id": "DEL-ROH",
        "zone": "Rohini",
        "city": "Delhi",
        "lat": 28.7410,
        "lng": 77.0674,
        "zone_multiplier": 1.20,
        "is_coastal": False,
        "avg_elevation_m": 220,
        "historical_rain_days": 25,
        "historical_aqi_gt300_days": 55,
        "historical_heat_gt44_days": 17,
    },
    {
        "zone_id": "DEL-DWA",
        "zone": "Dwarka",
        "city": "Delhi",
        "lat": 28.5921,
        "lng": 77.0460,
        "zone_multiplier": 1.15,
        "is_coastal": False,
        "avg_elevation_m": 213,
        "historical_rain_days": 24,
        "historical_aqi_gt300_days": 50,
        "historical_heat_gt44_days": 15,
    },
    {
        "zone_id": "DEL-SAK",
        "zone": "Saket",
        "city": "Delhi",
        "lat": 28.5245,
        "lng": 77.2066,
        "zone_multiplier": 1.10,
        "is_coastal": False,
        "avg_elevation_m": 208,
        "historical_rain_days": 27,
        "historical_aqi_gt300_days": 52,
        "historical_heat_gt44_days": 14,
    },
    {
        "zone_id": "DEL-NOI",
        "zone": "Noida Sector 18",
        "city": "Delhi",
        "lat": 28.5679,
        "lng": 77.3260,
        "zone_multiplier": 1.05,
        "is_coastal": False,
        "avg_elevation_m": 198,
        "historical_rain_days": 26,
        "historical_aqi_gt300_days": 48,
        "historical_heat_gt44_days": 13,
    },
    # Chennai
    {
        "zone_id": "CHE-TNA",
        "zone": "T. Nagar",
        "city": "Chennai",
        "lat": 13.0418,
        "lng": 80.2341,
        "zone_multiplier": 1.10,
        "is_coastal": False,
        "avg_elevation_m": 6,
        "historical_rain_days": 52,
        "historical_aqi_gt300_days": 8,
        "historical_heat_gt44_days": 22,
    },
    {
        "zone_id": "CHE-ADY",
        "zone": "Adyar",
        "city": "Chennai",
        "lat": 13.0012,
        "lng": 80.2565,
        "zone_multiplier": 1.15,
        "is_coastal": True,
        "avg_elevation_m": 4,
        "historical_rain_days": 58,
        "historical_aqi_gt300_days": 6,
        "historical_heat_gt44_days": 24,
    },
    {
        "zone_id": "CHE-ANN",
        "zone": "Anna Nagar",
        "city": "Chennai",
        "lat": 13.0850,
        "lng": 80.2101,
        "zone_multiplier": 1.05,
        "is_coastal": False,
        "avg_elevation_m": 8,
        "historical_rain_days": 50,
        "historical_aqi_gt300_days": 9,
        "historical_heat_gt44_days": 20,
    },
    {
        "zone_id": "CHE-VEL",
        "zone": "Velachery",
        "city": "Chennai",
        "lat": 12.9815,
        "lng": 80.2180,
        "zone_multiplier": 1.20,
        "is_coastal": False,
        "avg_elevation_m": 5,
        "historical_rain_days": 55,
        "historical_aqi_gt300_days": 7,
        "historical_heat_gt44_days": 21,
    },
    {
        "zone_id": "CHE-PON",
        "zone": "Porur",
        "city": "Chennai",
        "lat": 13.0358,
        "lng": 80.1572,
        "zone_multiplier": 1.00,
        "is_coastal": False,
        "avg_elevation_m": 10,
        "historical_rain_days": 48,
        "historical_aqi_gt300_days": 10,
        "historical_heat_gt44_days": 19,
    },
    {
        "zone_id": "CHE-CHR",
        "zone": "Chromepet",
        "city": "Chennai",
        "lat": 12.9516,
        "lng": 80.1462,
        "zone_multiplier": 0.95,
        "is_coastal": False,
        "avg_elevation_m": 12,
        "historical_rain_days": 46,
        "historical_aqi_gt300_days": 11,
        "historical_heat_gt44_days": 18,
    },
    # Bangalore
    {
        "zone_id": "BLR-KOR",
        "zone": "Koramangala",
        "city": "Bangalore",
        "lat": 12.9352,
        "lng": 77.6245,
        "zone_multiplier": 1.20,
        "is_coastal": False,
        "avg_elevation_m": 920,
        "historical_rain_days": 62,
        "historical_aqi_gt300_days": 15,
        "historical_heat_gt44_days": 0,
    },
    {
        "zone_id": "BLR-IND",
        "zone": "Indiranagar",
        "city": "Bangalore",
        "lat": 12.9784,
        "lng": 77.6408,
        "zone_multiplier": 1.10,
        "is_coastal": False,
        "avg_elevation_m": 912,
        "historical_rain_days": 60,
        "historical_aqi_gt300_days": 14,
        "historical_heat_gt44_days": 0,
    },
    {
        "zone_id": "BLR-WHI",
        "zone": "Whitefield",
        "city": "Bangalore",
        "lat": 12.9698,
        "lng": 77.7499,
        "zone_multiplier": 1.00,
        "is_coastal": False,
        "avg_elevation_m": 896,
        "historical_rain_days": 58,
        "historical_aqi_gt300_days": 18,
        "historical_heat_gt44_days": 0,
    },
    {
        "zone_id": "BLR-ELE",
        "zone": "Electronic City",
        "city": "Bangalore",
        "lat": 12.8399,
        "lng": 77.6770,
        "zone_multiplier": 0.95,
        "is_coastal": False,
        "avg_elevation_m": 880,
        "historical_rain_days": 55,
        "historical_aqi_gt300_days": 20,
        "historical_heat_gt44_days": 0,
    },
    {
        "zone_id": "BLR-JAY",
        "zone": "Jayanagar",
        "city": "Bangalore",
        "lat": 12.9299,
        "lng": 77.5826,
        "zone_multiplier": 1.05,
        "is_coastal": False,
        "avg_elevation_m": 905,
        "historical_rain_days": 59,
        "historical_aqi_gt300_days": 16,
        "historical_heat_gt44_days": 0,
    },
    {
        "zone_id": "BLR-MAL",
        "zone": "Malleswaram",
        "city": "Bangalore",
        "lat": 13.0035,
        "lng": 77.5673,
        "zone_multiplier": 0.90,
        "is_coastal": False,
        "avg_elevation_m": 918,
        "historical_rain_days": 57,
        "historical_aqi_gt300_days": 12,
        "historical_heat_gt44_days": 0,
    },
    # Hyderabad
    {
        "zone_id": "HYD-BAN",
        "zone": "Banjara Hills",
        "city": "Hyderabad",
        "lat": 17.4156,
        "lng": 78.4347,
        "zone_multiplier": 0.95,
        "is_coastal": False,
        "avg_elevation_m": 540,
        "historical_rain_days": 38,
        "historical_aqi_gt300_days": 22,
        "historical_heat_gt44_days": 28,
    },
    {
        "zone_id": "HYD-HIT",
        "zone": "HITEC City",
        "city": "Hyderabad",
        "lat": 17.4435,
        "lng": 78.3772,
        "zone_multiplier": 0.90,
        "is_coastal": False,
        "avg_elevation_m": 545,
        "historical_rain_days": 36,
        "historical_aqi_gt300_days": 20,
        "historical_heat_gt44_days": 26,
    },
    {
        "zone_id": "HYD-SEC",
        "zone": "Secunderabad",
        "city": "Hyderabad",
        "lat": 17.4399,
        "lng": 78.4983,
        "zone_multiplier": 1.00,
        "is_coastal": False,
        "avg_elevation_m": 536,
        "historical_rain_days": 40,
        "historical_aqi_gt300_days": 25,
        "historical_heat_gt44_days": 30,
    },
    {
        "zone_id": "HYD-KUK",
        "zone": "Kukatpally",
        "city": "Hyderabad",
        "lat": 17.4849,
        "lng": 78.3994,
        "zone_multiplier": 1.05,
        "is_coastal": False,
        "avg_elevation_m": 528,
        "historical_rain_days": 39,
        "historical_aqi_gt300_days": 28,
        "historical_heat_gt44_days": 32,
    },
    {
        "zone_id": "HYD-CHI",
        "zone": "Charminar",
        "city": "Hyderabad",
        "lat": 17.3616,
        "lng": 78.4747,
        "zone_multiplier": 1.10,
        "is_coastal": False,
        "avg_elevation_m": 525,
        "historical_rain_days": 42,
        "historical_aqi_gt300_days": 30,
        "historical_heat_gt44_days": 33,
    },
    {
        "zone_id": "HYD-LBN",
        "zone": "LB Nagar",
        "city": "Hyderabad",
        "lat": 17.3478,
        "lng": 78.5519,
        "zone_multiplier": 1.00,
        "is_coastal": False,
        "avg_elevation_m": 522,
        "historical_rain_days": 41,
        "historical_aqi_gt300_days": 26,
        "historical_heat_gt44_days": 29,
    },
]

ZONES_BY_ID: Dict[str, Dict[str, object]] = {
    str(zone["zone_id"]): zone for zone in ZONES
}

