"""
train_model7_prophet.py — updated for ML-DATASET-BLUEPRINT-v1.0
=================================================================
Trains one Prophet model per city_type (Chennai / Mumbai / Bangalore / Tier2)
using the new 3.9M-row prophet_training.csv generated by prophet_data_gen.py.

Improvements over v1:
  - seasonality_mode='multiplicative'  (v1 was additive — wrong for India)
  - External regressors: festival_multiplier, precipitation_mm,
    temperature_c, traffic_profile_index, salary_week_flag
  - Trains on 3 years of hourly data (2022–2024)
  - Saves backward-compat slugs for existing Chennai zone endpoints
    (adyar, velachery, tambaram … all share the Chennai model)
"""

import joblib
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

PROJECT_ROOT = Path(__file__).parent.parent.parent
MODELS_DIR   = PROJECT_ROOT / "outputs" / "trained_models"
PROPHET_CSV  = PROJECT_ROOT / "hustlr-ml" / "outputs" / "datasets" / "prophet_training.csv"

# External regressors available in the new CSV
REGRESSORS = [
    "festival_multiplier",
    "precipitation_mm",
    "temperature_c",
    "traffic_profile_index",
    "salary_week_flag",
]

# For backwards-compat: these slugs are loaded by the forecast endpoints.
# All map to the Chennai Prophet model.
CHENNAI_SLUG_ALIASES = [
    "adyar", "velachery", "tambaram", "anna_nagar",
    "t_nagar", "omr", "guindy", "chromepet",
    "perambur", "sholinganallur",
]


def zone_file_slug(name: str) -> str:
    return name.strip().lower().replace(" ", "_").replace("-", "_")


def train_prophet_all_zones():
    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    if not PROPHET_CSV.is_file():
        raise FileNotFoundError(f"Missing dataset: {PROPHET_CSV}")

    try:
        from prophet import Prophet
    except ImportError as e:
        raise ImportError("Install prophet: pip install prophet") from e

    print(f"Loading {PROPHET_CSV.name} ...")
    df = pd.read_csv(PROPHET_CSV)

    # Support both old schema ('zone' col) and new schema ('zone_id' + 'city_type')
    if "zone" in df.columns and "ds" in df.columns:
        # Old schema — use as-is
        df["city_type"] = df["zone"]
    elif "zone_id" in df.columns and "city_type" in df.columns:
        # New blueprint schema
        pass
    else:
        raise ValueError("prophet_training.csv needs either (zone, ds) or (zone_id, city_type, ds) columns")

    df["ds"] = pd.to_datetime(df["ds"])

    city_types = sorted(df["city_type"].astype(str).unique())
    print(f"Training Model 7 - Prophet for {len(city_types)} city types: {city_types}")

    city_models = {}

    for city in city_types:
        sub = df[df["city_type"] == city].copy()

        # Aggregate to daily by taking the mean across all zones of that city per timestamp
        # (Prophet works best on daily or lower frequency for 3-year spans)
        sub = sub.sort_values("ds")

        # Drop duplicates per timestamp by averaging
        agg_cols = {"y": "mean"}
        for reg in REGRESSORS:
            if reg in sub.columns:
                agg_cols[reg] = "mean"

        sub_daily = sub.groupby("ds").agg(agg_cols).reset_index()
        sub_daily = sub_daily.dropna(subset=["ds", "y"])

        if len(sub_daily) < 100:
            print(f"  skip {city}: only {len(sub_daily)} rows after aggregation")
            continue

        print(f"  fitting {city}: {len(sub_daily):,} hourly rows ...")

        # Log-transform target: demand_units = exp(log-space composite)
        # Prophet sees a near-additive series in log(y)
        sub_daily["y"] = np.log(sub_daily["y"].clip(lower=0.1))

        m = Prophet(
            seasonality_mode="multiplicative",    # CRITICAL: multiplicative for India
            changepoint_prior_scale=0.15,
            seasonality_prior_scale=12,
            daily_seasonality=True,
            weekly_seasonality=True,
            yearly_seasonality=True,
            mcmc_samples=0,                        # MAP estimation — required for Render
        )

        # Add regressors that exist in the data
        available_regs = [r for r in REGRESSORS if r in sub_daily.columns]
        for reg in available_regs:
            standardize = reg not in ("salary_week_flag", "ipl_match_flag")
            mode = "additive" if reg in ("salary_week_flag",) else "multiplicative"
            m.add_regressor(reg, standardize=standardize, mode=mode)

        m.add_seasonality(name="monthly", period=30.5, fourier_order=5)

        fit_df = sub_daily[["ds", "y"] + available_regs].copy()
        m.fit(fit_df)

        slug = zone_file_slug(city)
        out  = MODELS_DIR / f"model7_prophet_{slug}.pkl"
        joblib.dump(m, out)
        print(f"  saved {out.name} (regressors: {available_regs})")
        city_models[slug] = out

    # Backward-compat: create Chennai slug aliases so existing endpoints don't break
    if "chennai" in city_models:
        src = city_models["chennai"]
        m_chennai = joblib.load(src)
        for alias in CHENNAI_SLUG_ALIASES:
            alias_path = MODELS_DIR / f"model7_prophet_{alias}.pkl"
            joblib.dump(m_chennai, alias_path)
        print(f"  Created {len(CHENNAI_SLUG_ALIASES)} Chennai zone aliases -> chennai model")

    print("Prophet training finished.")


if __name__ == "__main__":
    train_prophet_all_zones()
